/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.Selecao;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Selecao</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SelecaoImpl extends GreetingImpl implements Selecao
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SelecaoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.SELECAO;
  }

} //SelecaoImpl
