/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Define</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Define#getSel <em>Sel</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getDefine()
 * @model
 * @generated
 */
public interface Define extends Greeting
{
  /**
   * Returns the value of the '<em><b>Sel</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sel</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sel</em>' containment reference.
   * @see #setSel(Selecao)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getDefine_Sel()
   * @model containment="true"
   * @generated
   */
  Selecao getSel();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Define#getSel <em>Sel</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sel</em>' containment reference.
   * @see #getSel()
   * @generated
   */
  void setSel(Selecao value);

} // Define
